version: '3.4'

services:
  schoolmanagementsystem-db:
    image: postgres:15-alpine   
    networks:
      - backend

  adminer:
    image: adminer
    networks:
      - backend
   

  schoolmanagementsystem.core.api:
    image: ${DOCKER_REGISTRY-}schoolmanagementsystem-core-api
    build:
      context: .
      dockerfile: SchoolManagementSystem.Core/Dockerfile
    networks:
      - backend



 
  schoolmanagementsystem.notification.api:
    image: ${DOCKER_REGISTRY-}schoolmanagementsystemnotificationapi
    build:
      context: .
      dockerfile: SchoolManagementSystem.Notification.Api/Dockerfile
    networks:
      - backend

  schoolmanagementsystem.newsletter.api:
    image: ${DOCKER_REGISTRY-}schoolmanagementsystem-newsletter-api
    build:
      context: .
      dockerfile: SchoolManagementSystem.Newsletter.Api/Dockerfile
    networks:
      - backend

networks:
   backend:
    name: Schoolmanagementsystem-network

volumes:
  data-postgres:



