version: '3.4'

services:
  schoolmanagementsystem.core.api:
    image: ${DOCKER_REGISTRY-}schoolmanagementsystemcoreapi
    build:
      context: .
      dockerfile: SchoolManagementSystem.Core/Dockerfile
